; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_qtpy_esp32c3]
platform = espressif32
board = adafruit_qtpy_esp32c3
framework = arduino
build_flags = -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	adafruit/Adafruit BME680 Library@^2.0.5
	mbed-edamame22/MiCS6814_GasSensor@0.0.0+sha.a15eee9bb0e6
	mbed-cognoscan/Adafruit_ST7735@0.0.0+sha.20134e1718b2
	adafruit/Adafruit GFX Library@^1.12.4
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
	adafruit/Adafruit AS7341@^1.4.1
